### PR TITLE
Project AreWeReorganizedYetum

### PR DESCRIPTION
**Pull request by bnjbvr**

### CODE REVIEW

**Comment by sylvestre** [comment]
No unit tests?!

**Comment by bnjbvr** [comment]
@sylvestre, would you like to act as the release manager of AreWeReorganizedYetum? (this should not involve any reorganization)

**Comment by adngdb** [comment]
I think I hate you for making me review that... I'm amazed by the complexity this project is getting!

**Comment by adngdb** [comment]
https://i.imgur.com/APigjvz.gifv

**Pull request merged**
