### PR TITLE
Display days since last reorg.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
@bnjbvr r?

### CODE REVIEW

**Comment by bnjbvr** [comment]
I assume you've tested it, so r=me

**Comment by bnjbvr** [comment]
nit: `days` doesn't take the plural form if num of days is 0.

**Comment by AdrianGaudebert** [comment]
WRONG. It should not have an -s when the number is 1, but it should have one when the number is 0. http://english.stackexchange.com/questions/13073/correct-plural-form-of-a-zero-quantified-noun

(I guess that would make a good first bug. mentor=me. )

**Comment by bnjbvr** [comment]
Ha, I really meant to write 1.
And wait, where did you see 0 in my previous comment? :P

**Comment by AdrianGaudebert** [comment]
Right there, man, right there. 

YOU DONE GOOFED.

**Pull request merged**
